# Generated by Django 5.2.3 on 2025-06-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0002_doctor_patient_patientdoctormapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
