# Generated by Django 5.2.3 on 2025-06-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0003_alter_doctor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(to='Health.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='PatientDoctorMapping',
        ),
    ]
