# Generated by Django 5.2.3 on 2025-06-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0004_patient_doctor_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
    ]
