# Generated by Django 5.2.3 on 2025-06-24 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0005_remove_patient_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Health.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Health.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(related_name='patients', through='Health.Intermediate', to='Health.doctor'),
        ),
    ]
